### ISSUE TITLE
Cannot display data when I upload to my own cloud

### ISSUE THREAD

**Issue by Bynow76** [rmeertens/ImmersivePoints#1]
The URL obtained from the uploaded page can be displayed, but the URL generated by this code cannot display the point cloud. I uploaded the generated numpy data to Alibaba Cloud

**Comment by rmeertens** [comment]
Hey @Bynow76 . Happy to help out! Can you give me the link to your uploaded numpy data? 
One thing to check is whether the cors (cross-origin resource sharing) is turned on. You can enable it this way: https://docs.sevenbridges.cn/docs/enabling-cross-origin-resource-sharing-cors

**Comment by Bynow76** [comment]
> Hey @Bynow76 . Happy to help out! Can you give me the link to your uploaded numpy data?
> One thing to check is whether the cors (cross-origin resource sharing) is turned on. You can enable it this way: https://docs.sevenbridges.cn/docs/enabling-cross-origin-resource-sharing-cors



> Hey @Bynow76 . Happy to help out! Can you give me the link to your uploaded numpy data?
> One thing to check is whether the cors (cross-origin resource sharing) is turned on. You can enable it this way: https://docs.sevenbridges.cn/docs/enabling-cross-origin-resource-sharing-cors

**Comment by Bynow76** [comment]
> Hey @Bynow76 . Happy to help out! Can you give me the link to your uploaded numpy data?
> One thing to check is whether the cors (cross-origin resource sharing) is turned on. You can enable it this way: https://docs.sevenbridges.cn/docs/enabling-cross-origin-resource-sharing-cors

Thanks a lot! I have figured out it!

**Comment by rmeertens** [comment]
Awesome news! Let me know if you have any cool demos, are missing
functionality, or particularly like something!

Op za 19 sep. 2020 om 15:24 schreef Bynow76 <notifications@github.com>:
